// const promiseOne = new Promise(function(resolve, reject){
//     setTimeout(function(){
//         console.log('Async task is done');
        //  resolve();
//       }, 1000)
// })

// promiseOne.then(function(){
//     console.log("promise consumed"); 
// })



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
//      let promise = new Promise(function(resolve, reject){
//     setTimeout(function(){
//         resolve({username:"krrish", email:"chai@.com"})
//     },1000);
// }).then(function(){
//     console.log("asyn 2 resolve");
    
// }); 
 
const promisefouth = new Promise(function(resolve,reject){
    setTimeout(function(){
    let error=true
    if (!error) {
        resolve({username:"krrish",password:1234})
    }else{
        reject('ERROR:Something went wrong')
    }
    },1000)
})
 promisefouth.then((user)=>{
    console.log(user);
    return user.username
}).then((username)=>{
console.log(username);
}).catch(function(error){
    console.log(error);
}).finally(() => console.log("promise is either reslove or rejected")
)

const promisefifth = new Promise(function(reslove, reject){
    setTimeout(function(){
        let error = true
        if (!error) {
           reslove({username:"javascript", password:"456"})
        }else{
            reject('ERROR:js went wrong')
        }
    },1000)
})

async function consumepromisefifth(){
//    const response =  await promisefifth
//    console.log(response);      or
try {
    const response =  await promisefifth
    console.log(response);
} catch (error) {
    console.log(error);
}
   consumepromisefifth()


}
//    async function getallUsers() {
//     try {
//           const response = await fetch('https://jsonplaceholder.typicode.com/users')
//           const data = await response.json() //.json took time that's why we need to await it
//           console.log(data);
//     } catch (error) {
//         console.log("E: ", error);
        
//     }
//    }

// getallUsers()

fetch('https://jsonplaceholder.typicode.com/users')
.then((response) =>{
    return response.json() // once it finish
})
.then((data) =>{
    console.log(data);// then this ot starting 
})
.catch((error) =>console.log(error))

</script>
</html>